# Generated by Django 4.2.28 on 2026-02-21 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vegflow_parties', '0001_initial'),
        ('vegflow_products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VegflowSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], default='cash', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegflow_sales', to='vegflow_parties.vegflowcustomer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegflow_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vegflow_billing_sale',
                'ordering': ['-sale_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VegflowSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegflow_products.vegflowproduct')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vegflow_billing.vegflowsale')),
            ],
            options={
                'db_table': 'vegflow_billing_sale_item',
            },
        ),
    ]
