# Generated by Django 4.2.28 on 2026-02-21 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vegflow_expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegflowStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegflow_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vegflow_expenses_staff',
                'ordering': ['name'],
            },
        ),
    ]
